### ISSUE TITLE
Cannot call class as function

### ISSUE THREAD

**Issue by ryanmcclure4** [formsy/formsy-react#119] opened 2018-09-30 23:34 UTC
I'm using formsy-react in a project which I recently upgraded to React 16 and Babel 7. After doing so, I now get the following error when trying to render form elements:

![image](https://user-images.githubusercontent.com/9887662/46264170-441f2900-c4ce-11e8-86ef-0e692f1a0b4b.png)

When logging in the _classCallCheck, I see that `this` is undefined. Any ideas on what's going on here?

**Comment by twisty** [comment] 2018-10-01 10:08
Need more detail to help with this. Can you give us details of your `package.json` and `.babelrc`?

**Comment by twisty** [comment] 2018-10-08 07:55
Hope you solved your issue. I'm going to close this one, due to lack of timely feedback. If you are still having problems, please open a new issue with steps to reproduce.

**Closed by twisty** 2018-10-08 07:55 UTC
